# Generated by Django 5.2.7 on 2025-10-28 05:19

from django.db import migrations


CATEGORIES = {
    "MAT": "Materials",
    "LOC": "Location",
    "FIN": "Final Item",
}

# This list defines the items you want to add initially
INITIAL_ITEMS = [
    {"name": "WOOD", "category": CATEGORIES["MAT"]},
    {"name": "STONE", "category": CATEGORIES["MAT"]},
    {"name": "FIRE", "category": CATEGORIES["MAT"]},
    {"name": "WATER", "category": CATEGORIES["MAT"]},
    {"name": "LAND", "category": CATEGORIES["LOC"]},
    {"name": "SHANK", "category": CATEGORIES["FIN"]},
    {"name": "STICK", "category": CATEGORIES["MAT"]},

]

# Item1, Item2, Result
INITIAL_RECIPES = [("WOOD", "WOOD", "STICK"), ("STICK", "STONE", "SHANK")]


def add_initial_items(apps, schema_editor):
    Item = apps.get_model('smithy', 'Item')
    CraftingRecipe = apps.get_model('smithy', 'CraftingRecipe') 
    print("\nAdding initial items...")

    for item_data in INITIAL_ITEMS:
        obj, created = Item.objects.get_or_create(
            name=item_data["name"],
            defaults={'category': item_data["category"]}
        )
        
        if created:
            print(f"  Created: {obj.name} (Category: {obj.category})")
        else:
            print(f"  Skipped (already exists): {obj.name}")
    print("\nAdding initial recipes...")

    for a_name, b_name, result_name in INITIAL_RECIPES:
        try:
            # Get the actual Item objects from the DB
            item_a = Item.objects.get(name=a_name)
            item_b = Item.objects.get(name=b_name)
            result_item = Item.objects.get(name=result_name)

            # Now create the recipe using the objects
            recipe, created = CraftingRecipe.objects.get_or_create(
                item_a=item_a,
                item_b=item_b,
                defaults={'result': result_item}
            )

            if created:
                print(
                    f"  Created recipe: {item_a.name} + "
                    f" {item_b.name} = {result_item.name}")
            else:
                print(f"  Skipped recipe (already exists): "
                      f"{item_a.name} + {item_b.name}")

        except Item.DoesNotExist:
            print(f"  ERROR: Could not create recipe. Item not found for: "
                  f"{a_name}, {b_name}, or {result_name}")


def remove_initial_items(apps, schema_editor):
    Item = apps.get_model('smithy', 'Item')
    CraftingRecipe = apps.get_model('smithy', 'CraftingRecipe')

    item_names = [item["name"] for item in INITIAL_ITEMS]
    # get items from recipes, a set to handle  dupes
    result_names = {recipe[2] for recipe in INITIAL_RECIPES}

    # remove decipes
    recipes_to_delete = CraftingRecipe.objects.filter(
        result__name__in=result_names
    )
    count, _ = recipes_to_delete.delete()
    print(f"{count}, is deleted")

    # delete all items from list
    items_to_delete = Item.objects.filter(name__in=item_names)
    count, _ = items_to_delete.delete()
    print(f"{count}, is deleted")


class Migration(migrations.Migration):
    dependencies = [
        ('smithy', '0001_initial'),
    ]

    operations = [
        # This tells Django to run our custom functions
        migrations.RunPython(add_initial_items, remove_initial_items)]
