# Generated by Django 5.2.7 on 2025-12-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smithy', '0003_craftingrecipe_discovered_userlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='craftingrecipe',
            unique_together={('item_a', 'item_b')},
        ),
        migrations.RemoveField(
            model_name='craftingrecipe',
            name='discovered',
        ),
    ]
